services:
  homeassistant:
    container_name: homea-ssistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /root/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    networks:
      - home-assistant

networks:
  home-assistant:
    external: true