services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    volumes:
      - /root/beszel:/beszel_data
    networks:
      beszel:
      SDB1:
        ipv4_address: ${ip_address}
    environment:
      USER_CREATION: true
      APP_URL: ${APP_URL}

networks:
  beszel:
    external: true
  SDB1:
    external: true