services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    volumes:
      - /root/beszel:/beszel_data
    networks:
      - beszel
    environment:
      USER_CREATION: ${USER_CREATION}

networks:
  beszel:
    external: true