services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    volumes:
      - /rooot/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /root/StirlingPDF/extraConfigs:/configs
      - /root/StirlingPDF/customFiles:/customFiles/
      - /root/StirlingPDF/logs:/logs/
      - /root/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB